version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dispro-api
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network
    ports:
      - "80:8080"
    command: php artisan serve --host=0.0.0.0 --port=8080

networks:
  app-network:
    driver: bridge
