name: Laravel CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: dispro_api
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - uses: actions/checkout@v4

    - name: Copier le fichier .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Installer les dépendances
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Générer la clé d'application
      run: php artisan key:generate

    - name: Configurer les permissions des répertoires
      run: chmod -R 777 storage bootstrap/cache

    - name: Exécuter les migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: dispro_api
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan migrate

    

   
